# =============================================================================
# update_directory_md.ps1
# Regenerates DIRECTORY.md (the live directory map) from the actual cpcs/ tree.
# MANDATORY: run this after adding, removing, or renaming any route/folder.
# Usage: pwsh -NoProfile -File .\update_directory_md.ps1
# =============================================================================
param(
    [string]$Root    = (Join-Path $PSScriptRoot 'cpcs'),
    [string]$OutFile = (Join-Path $PSScriptRoot 'DIRECTORY.md')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path -LiteralPath $Root)) {
    throw "Root not found: $Root"
}

function Render-Tree {
    param([string]$Path, [string]$Prefix)
    $dirs = Get-ChildItem -LiteralPath $Path -Directory | Sort-Object Name
    for ($i = 0; $i -lt $dirs.Count; $i++) {
        $isLast = ($i -eq $dirs.Count - 1)
        $connector = if ($isLast) { [char]0x2514 + ([string][char]0x2500)*2 + ' ' }
                     else          { [char]0x251C + ([string][char]0x2500)*2 + ' ' }
        "$Prefix$connector$($dirs[$i].Name)/"
        $extension = if ($isLast) { '    ' } else { ([string][char]0x2502) + '   ' }
        Render-Tree -Path $dirs[$i].FullName -Prefix ($Prefix + $extension)
    }
}

$rootName   = Split-Path -Leaf $Root
$totalDirs  = (Get-ChildItem -LiteralPath $Root -Recurse -Directory).Count + 1
$leafDirs   = (Get-ChildItem -LiteralPath $Root -Recurse -Directory |
               Where-Object { -not (Get-ChildItem -LiteralPath $_.FullName -Directory) }).Count
$timestamp  = (Get-Date).ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss') + ' UTC'

$treeLines = @("$rootName/")
$treeLines += @(Render-Tree -Path $Root -Prefix '')

$md = @"
# CPCS Directory Map (LIVE)

> **MANDATORY FILE.** This document is the live index of every route in the
> ``cpcs/`` tree. It MUST be regenerated whenever a route is added, removed,
> or renamed:
>
> ``````pwsh
> pwsh -NoProfile -File .\update_directory_md.ps1
> ``````
>
> Do not hand-edit the tree below; it is generated from the filesystem.

| Property | Value |
| --- | --- |
| Last updated | $timestamp |
| Root | ``$rootName/`` |
| Total routes | $totalDirs |
| Leaf routes | $leafDirs |

## Route Tree

``````text
$($treeLines -join "`n")
``````

---
_Generated by ``update_directory_md.ps1``. Never edit this file manually._
"@

Set-Content -LiteralPath $OutFile -Value $md -Encoding utf8 -NoNewline
Add-Content -LiteralPath $OutFile -Value "`n" -Encoding utf8 -NoNewline

Write-Host "DIRECTORY.md updated: $totalDirs routes ($leafDirs leaves) as of $timestamp"
